[package]
name = "ranch"
version = "0.6.0"
edition = "2024"
description = "Ranged integer types and math"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
documentation = "https://docs.rs/ranch"
homepage = "https://github.com/AldaronLau/ranch/releases"
repository = "https://github.com/AldaronLau/ranch"
readme = "README.md"
keywords = ["ranged", "int", "const", "generics", "integers"]
categories = [
    "development-tools::ffi",
    "mathematics",
    "no-std::no-alloc",
    "parsing",
    "rust-patterns",
]
include = [
    "/LICENSE_APACHE",
    "/LICENSE_BOOST",
    "/LICENSE_MIT",
    "/README.md",
    "/examples/*",
    "/src/*",
]
rust-version = "1.91"

[package.metadata.docs.rs]
all-features = true

[dependencies.arbitrary]
version = "1.4.2"
optional = true
default-features = false

[dependencies.as_repr]
package = "as_repr-core"
version = "1.7.0"
default-features = false

[dependencies.bitflags]
version = "2.13.0"
optional = true
default-features = false

[dependencies.bytemuck]
version = "1.25.0"
optional = true
default-features = false

[dependencies.fastrand]
version = "2.4.0"
optional = true
default-features = false

[dependencies.rand]
version = "0.10.1"
optional = true
default-features = false

[dependencies.serde_core]
version = "1.0.228"
optional = true
default-features = false

[dependencies.zeroize]
version = "1.8.2"
optional = true
default-features = false

[dev-dependencies.rand]
version = "0.10.0"
default-features = false
features = ["thread_rng"]

[dev-dependencies.serde]
version = "1.0.228"
default-features = false
features = ["derive"]

[dev-dependencies.serde_json]
version = "1.0.150"
default-features = false
features = ["std"]

[features]
"default" = ["full"]
"full" = []

"arbitrary" = ["arbitrary.v1"]
"arbitrary.v1" = ["dep:arbitrary", "full"]
"bitflags" = ["bitflags.v2"]
"bitflags.v2" = ["dep:bitflags", "full"]
"bytemuck" = ["bytemuck.v1"]
"bytemuck.v1" = ["dep:bytemuck", "full"]
"fastrand" = ["fastrand.v2"]
"fastrand.v2" = ["dep:fastrand", "full"]
"rand.v010" = ["dep:rand", "full"]
"serde" = ["serde.v1"]
"serde.v1" = ["dep:serde_core", "full"]
"zeroize" = ["zeroize.v1"]
"zeroize.v1" = ["dep:zeroize", "full"]
