name: checks
on:
  push:
    branches: ['v*']
  pull_request:
jobs:
  miri:
    name: "Miri (safety and big-endian testing)"
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test --all --all-features
      - name: Test with Miri (big-endian)
        run: cargo miri test --all --all-features --target s390x-unknown-linux-gnu
  verify:
    name: "Verify (unit tests pass, format correct, & docs generate)"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [1.85.0, stable, beta, nightly]
        include:
        - tc: stable
          up: cargo update
        - tc: beta
          up: cargo update
        - tc: nightly
          up: cargo update
    steps:
      - uses: taiki-e/checkout-action@v1
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup default ${{ matrix.tc }}
          rustup component add rustfmt
      - if: ${{ matrix.up }}
        name: Updating dependencies
        run: ${{ matrix.up }}
      - if: ${{ matrix.up }}
        name: Running tests
        run: |
          cargo test --all
          cargo test --all --all-features
      - name: Check code formatting
        run: cargo fmt --check
      - name: Check doc generation succeeds
        run: cargo doc --all-features
  cross-compile:
    name: "Cross-compilation (clippy & builds)"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.85.0, stable, beta, nightly]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasip1
        - wasm32-unknown-unknown
        - x86_64-apple-darwin
        - x86_64-unknown-redox
        - x86_64-unknown-illumos
        include:
        - os: macos-latest
          tc: 1.85.0
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: stable
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: beta
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: nightly
          cc: aarch64-apple-ios
    steps:
      - uses: taiki-e/checkout-action@v1
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup default ${{ matrix.tc }}
          rustup component add clippy
          rustup target add ${{ matrix.cc }}
      - name: Assert clippy checks pass
        run: |
          cargo clippy --workspace --all-targets --target=${{ matrix.cc }} -- -D warnings
          cargo clippy --workspace --all-targets --all-features --target=${{ matrix.cc }} -- -D warnings
      - name: Build for cross-compilation target
        run: |
          cargo build --target=${{ matrix.cc }}
          cargo build --all-features --target=${{ matrix.cc }}
